[package]
name = "restriction_for_diesel"
version = "0.1.0"
authors = ["zzt <369815332@qq.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["full", "fold"] }
quote = "0.6"
proc-macro2 = "0.4"